openapi: 3.0.0
info:
  title: Agentic Workflow API
  version: "1.0"
  description: API for orchestrating research agents and interacting with search and extraction tools.

servers:
  - url: http://localhost:8000
    description: Agentic Server (Orchestrator)
  - url: http://localhost:5000
    description: Search and Extraction Services

paths:
  /api/agent/execute:
    post:
      summary: Execute a new research job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResearchRequest'
      responses:
        '200':
          description: Job successfully initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'

  /api/agent/status/{job_id}:
    get:
      summary: Get the status of a job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'

  /api/agent/results/{job_id}:
    get:
      summary: Get the final results of a job
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResult'

  /api/tools/search:
    post:
      summary: Search for academic papers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'

  /api/tools/extract:
    post:
      summary: Extract content from a source
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtractionRequest'
      responses:
        '200':
          description: Extracted content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractionResponse'

components:
  schemas:
    # Agentic Server Schemas
    ResearchRequest:
      type: object
      required:
        - research_goal
      properties:
        research_goal:
          type: string
          minLength: 10
          maxLength: 500
        scope_parameters:
          type: object
          properties:
            temporal_boundary:
              type: object
              properties:
                publication_window_years:
                  type: number
                  minimum: 1
                  maximum: 10
                  default: 3
            quality_threshold:
              type: object
              properties:
                impact_level:
                  type: string
                  enum: ["cutting_edge", "high_impact", "established", "baseline"]
            discovery_depth:
              type: string
              enum: ["rapid", "focused", "comprehensive", "exhaustive"]
            source_diversity_requirement:
              type: boolean
              default: true

    JobResponse:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
        status:
          type: string
        autonomous_analysis:
          type: object
          properties:
            goal_decomposition:
              type: object
              properties:
                primary_objectives:
                  type: array
                  items:
                    type: string
                sub_goals:
                  type: array
                  items:
                    type: string
            execution_strategy:
              type: object
              properties:
                search_approach:
                  type: string
                validation_rules:
                  type: array
                  items:
                    type: string
            governance_applied:
              type: object
              properties:
                policies_checked:
                  type: array
                  items:
                    type: string
        execution_plan:
          type: object
          properties:
            phases:
              type: array
              items:
                type: object
                properties:
                  phase:
                    type: string
                  description:
                    type: string
            estimated_sources:
              type: integer
            estimated_duration_minutes:
              type: integer

    JobStatus:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
        status:
          type: string
        current_phase:
          type: object
          properties:
            phase_name:
              type: string
            phase_description:
              type: string
            progress_percentage:
              type: integer
            intelligent_actions_taken:
              type: array
              items:
                type: string
        autonomous_decisions:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
              decision_type:
                type: string
              reasoning:
                type: string
              action_taken:
                type: string
        quality_metrics:
          type: object
          properties:
            sources_discovered:
              type: integer
            sources_validated:
              type: integer
            sources_accepted:
              type: integer
            sources_rejected:
              type: integer
            average_quality_score:
              type: number
              format: float

    JobResult:
      type: object
      properties:
        job_id:
          type: string
          format: uuid
        status:
          type: string
        synthesis:
          type: object
          properties:
            research_goal:
              type: string
            executive_summary:
              type: string
            synthesis_text:
              type: string
            primary_themes:
              type: array
              items:
                type: string
            gaps_identified:
              type: array
              items:
                type: string
            sources_analyzed:
              type: integer
            methodologies_found:
              type: integer
        execution_summary:
          type: object
          properties:
            total_sources_discovered:
              type: integer
            sources_validated:
              type: integer
            extractions_successful:
              type: integer
        audit_trail_summary:
          type: object
          properties:
            total_decisions_logged:
              type: integer
            full_audit_log_available:
              type: boolean

    # Search Service Schemas
    SearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          minLength: 1
          maxLength: 500
        filters:
          type: object
          properties:
            year_range:
              type: object
              properties:
                start:
                  type: integer
                end:
                  type: integer
            source_types:
              type: array
              items:
                type: string
                enum: ["academic", "technical", "news"]
            min_quality_score:
              type: number
              format: float
        max_results:
          type: integer
          default: 20

    SearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              title:
                type: string
              snippet:
                type: string
              relevance_score:
                type: number
                format: float
              year:
                type: integer
              citations:
                type: integer
              authors:
                type: array
                items:
                  type: string
              venue:
                type: string
              doi:
                type: string
        total_found:
          type: integer
        search_metrics:
          type: object
          properties:
            query_time_ms:
              type: integer
            sources_searched:
              type: integer

    # Extraction Service Schemas
    ExtractionRequest:
      type: object
      required:
        - source_url
      properties:
        source_url:
          type: string
        extraction_parameters:
          type: object
          properties:
            focus_areas:
              type: array
              items:
                type: string
            required_elements:
              type: array
              items:
                type: string
            max_length:
              type: integer

    ExtractionResponse:
      type: object
      properties:
        extracted_content:
          type: object
          properties:
            title:
              type: string
            abstract:
              type: string
            key_findings:
              type: array
              items:
                type: string
            methodology:
              type: string
            citations:
              type: array
              items:
                type: string
        metadata:
          type: object
          required:
            - extraction_success
          properties:
            extraction_success:
              type: boolean
            source_url:
              type: string
            extraction_timestamp:
              type: string
              format: date-time
            failure_reason:
              type: string
        extraction_metrics:
          type: object
          properties:
            processing_time_ms:
              type: integer
            confidence_score:
              type: number
              format: float
